In [1]:
%pwd

'c:\\Users\\Ayush\\OneDrive\\Desktop\\smart-traffic\\notebooks'

In [2]:
import os

In [3]:
os.chdir("../")

In [4]:
%pwd

'c:\\Users\\Ayush\\OneDrive\\Desktop\\smart-traffic'

In [5]:
from src.ingestion.data_ingestion import DataIngestion

ingestor = DataIngestion()

df_accidents = ingestor.load_csv(
    folder="accidents",
    file_name="LargeCitiesRoadAccidentsandFatalities2023.csv"
)

df_accidents.head()

[INFO] Loaded CSV: LargeCitiesRoadAccidentsandFatalities2023.csv, Shape: (51, 14)

,Sl No,City,2022 Accidents,2023 Accidents,2022 Ranking Accidents,2023 Ranking Accidents,2022 Killed,2023 Killed,2022 Ranking Killed,2023 Ranking Killed,2022 Injured,2023 Injured,2022 Ranking Injured,2023 Ranking Injured
0,1.0,Agra,"1,029","1,007",28.0,29.0,548,499,9.0,11.0,795,657,29.0,31.0
1,2.0,Ahmedabad,"1,711","1,767",19.0,19.0,488,535,11.0,8.0,"1,305","1,347",21.0,21.0
2,3.0,Allahabad (Prayagraj),"1,370","1,297",24.0,24.0,603,582,6.0,5.0,886,865,28.0,28.0
3,4.0,Amritsar,117,147,50.0,50.0,82,110,48.0,48.0,62,73,50.0,50.0
4,5.0,Asansol Durgapur,494,500,40.0,42.0,359,353,17.0,17.0,309,271,44.0,44.0

In [9]:
df_traffic = ingestor.load_excel(
    folder="traffic",
    file_name="Final_Majestic_to_AIM_jan-2016tomarch-2018.xlsx"
)
df_traffic.head()

[INFO] Loaded Excel: Final_Majestic_to_AIM_jan-2016tomarch-2018.xlsx, Shape: (821, 23)

,Date,Origin Movement ID,Origin Display Name,Destination Movement ID,Destination Display Name,Daily Mean Travel Time (Seconds),Daily Range - Lower Bound Travel Time (Seconds),Daily Range - Upper Bound Travel Time (Seconds),AM Mean Travel Time (Seconds),AM Range - Lower Bound Travel Time (Seconds),...,PM Range - Upper Bound Travel Time (Seconds),Midday Mean Travel Time (Seconds),Midday Range - Lower Bound Travel Time (Seconds),Midday Range - Upper Bound Travel Time (Seconds),Evening Mean Travel Time (Seconds),Evening Range - Lower Bound Travel Time (Seconds),Evening Range - Upper Bound Travel Time (Seconds),Early Morning Mean Travel Time (Seconds),Early Morning Range - Lower Bound Travel Time (Seconds),Early Morning Range - Upper Bound Travel Time (Seconds)
0,2017-04-04 00:00:00,100,"Kempegowda, Majestic, Bengaluru, Karnataka",171,"Analytics India Magazine, #280, 2nd floor, 5th...",2725,1841,4032,2780.0,2153.0,...,5001,3197.0,2483.0,4117.0,2615,1884,3629,1552,1224,1969
1,2017-05-04 00:00:00,100,"Kempegowda, Majestic, Bengaluru, Karnataka",171,"Analytics India Magazine, #280, 2nd floor, 5th...",2859,1952,4188,2945.0,2225.0,...,5004,2955.0,2356.0,3706.0,2719,1991,3714,1383,1161,1648
2,2017-06-04 00:00:00,100,"Kempegowda, Majestic, Bengaluru, Karnataka",171,"Analytics India Magazine, #280, 2nd floor, 5th...",2951,1990,4376,2715.0,2048.0,...,4975,3336.0,2565.0,4339.0,3078,2184,4340,1483,1218,1805
3,2017-07-04 00:00:00,100,"Kempegowda, Majestic, Bengaluru, Karnataka",171,"Analytics India Magazine, #280, 2nd floor, 5th...",2913,2058,4123,2788.0,2145.0,...,5152,2857.0,2287.0,3569.0,3411,2668,4360,1559,1303,1864
4,2017-08-04 00:00:00,100,"Kempegowda, Majestic, Bengaluru, Karnataka",171,"Analytics India Magazine, #280, 2nd floor, 5th...",2845,1954,4142,2423.0,1877.0,...,4685,3180.0,2676.0,3778.0,3100,2284,4207,1468,1182,1822

In [10]:
def validate_dataframe(df: pd.DataFrame):
    print("\n[VALIDATION REPORT]")
    print("Shape:", df.shape)
    print("Missing Values:\n", df.isnull().sum())
    print("Duplicate Rows:", df.duplicated().sum())

In [11]:
validate_dataframe(df_accidents)
validate_dataframe(df_traffic)

[VALIDATION REPORT]
Shape: (51, 14)
Missing Values:
 Sl No                     1
City                      0
2022 Accidents            0
2023 Accidents            0
2022 Ranking Accidents    1
2023 Ranking Accidents    1
2022 Killed               0
2023 Killed               0
2022 Ranking Killed       1
2023 Ranking Killed       1
2022 Injured              0
2023 Injured              0
2022 Ranking Injured      1
2023 Ranking Injured      1
dtype: int64
Duplicate Rows: 0

[VALIDATION REPORT]
Shape: (821, 23)
Missing Values:
 Date                                                       0
Origin Movement ID                                         0
Origin Display Name                                        0
Destination Movement ID                                    0
Destination Display Name                                   0
Daily Mean Travel Time (Seconds)                           0
Daily Range - Lower Bound Travel Time (Seconds)            0
Daily Range - Upper Bound Travel Time (Seconds)            0
AM Mean Travel Time (Seconds)                              1
AM Range - Lower Bound Travel Time (Seconds)               1
AM Range - Upper Bound Travel Time (Seconds)               1
PM Mean Travel Time (Seconds)                              0
PM Range - Lower Bound Travel Time (Seconds)               0
PM Range - Upper Bound Travel Time (Seconds)               0
Midday Mean Travel Time (Seconds)                          1
Midday Range - Lower Bound Travel Time (Seconds)           1
Midday Range - Upper Bound Travel Time (Seconds)           1
Evening Mean Travel Time (Seconds)                         0
Evening Range - Lower Bound Travel Time (Seconds)          0
Evening Range - Upper Bound Travel Time (Seconds)          0
Early Morning Mean Travel Time (Seconds)                   0
Early Morning Range - Lower Bound Travel Time (Seconds)    0
Early Morning Range - Upper Bound Travel Time (Seconds)    0
dtype: int64
Duplicate Rows: 0